addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
    - wget https://github.com/resteasy/resteasy-examples/blob/20e94d3b55c25fbfd3783434d58c2e0f0318070a/jenkins_data/jce_policy-8.zip
    - "sudo unzip -j -o jce_policy-8.zip *.jar -d $JAVA_HOME/jre/lib/security"
#install:
# - git clone https://github.com/resteasy/Resteasy.git
# - cd Resteasy
# - git checkout 3.6
# - mvn clean install -DskipTests=true
# - cd ..
# - mvn clean
script:
 - travis_wait 30 mvn -B install -Dorg.eclipse.jetty.annotations.maxWait=180

language: java
jdk:
  - oraclejdk8
cache:
 directories:
  - $HOME/.m2


